import requests
from moviepy.editor import *
import os
import json
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# --- CONFIG ---
# For testing: set a direct Bark output URL here (later Make will pass this)
BARK_AUDIO_URL = os.getenv("BARK_AUDIO_URL", "YOUR_BARK_AUDIO_URL")

# Background image/video for Shorts (put a file in repo or link to one)
BACKGROUND_IMAGE = "background.jpg"

# --- 1. Download audio ---
print("🔊 Downloading Bark audio...")
audio_data = requests.get(BARK_AUDIO_URL).content
with open("voice.wav", "wb") as f:
    f.write(audio_data)

# --- 2. Load audio & background ---
print("🎞️ Combining audio & background...")
audio = AudioFileClip("voice.wav")
background = ImageClip(BACKGROUND_IMAGE).set_duration(audio.duration)

# Resize to Shorts (9:16)
video = background.set_audio(audio).resize((1080, 1920))

video.write_videofile("output.mp4", fps=30, codec="libx264", audio_codec="aac")

print("✅ Video created: output.mp4")

# --- 3. Upload to YouTube Shorts ---
print("📤 Uploading to YouTube Shorts...")

# Load YouTube credentials from secrets.json
creds = Credentials.from_authorized_user_info(
    json.loads(os.getenv("YT_CREDS_JSON")),
    ["https://www.googleapis.com/auth/youtube.upload"]
)

youtube = build("youtube", "v3", credentials=creds)

body = {
    "snippet": {
        "title": "Auto POV Short #1",
        "description": "Scary POV Short generated by my AI bot 🤖",
        "tags": ["AI", "Shorts", "Horror"],
        "categoryId": "22"  # People & Blogs
    },
    "status": {
        "privacyStatus": "public",
        "selfDeclaredMadeForKids": False
    }
}

media = MediaFileUpload("output.mp4", chunksize=-1, resumable=True)

request = youtube.videos().insert(
    part="snippet,status",
    body=body,
    media_body=media
)

response = None
while response is None:
    status, response = request.next_chunk()
    if status:
        print(f"Uploading... {int(status.progress() * 100)}%")

print(f"✅ Uploaded: https://www.youtube.com/watch?v={response['id']}")
