name: Auto POV Bot

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      

      - name: Install Python dependencies
        run: |
          which python
          python -m pip install --upgrade pip
          python -m pip install --upgrade moviepy
          python -m pip install -r requirements.txt
          python -m pip show moviepy

      - name: Run bot with same python
        env:
          BARK_AUDIO_URL: ${{ secrets.BARK_AUDIO_URL }}
          YT_CREDS_JSON: ${{ secrets.YT_CREDS_JSON }}
        run: |
          which python
          python main.py
      - name: Create virtualenv
        run: |
          
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip show moviepy
          python main.py

