name: Auto POV Bot

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Debug installed packages
        run: |
          which python
          python --version
          pip list

      - name: Run bot
        env:
          BARK_AUDIO_URL: ${{ secrets.BARK_AUDIO_URL }}
          YT_CREDS_JSON: ${{ secrets.YT_CREDS_JSON }}
        run: python main.py
