name: Auto POV Bot

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python & FFmpeg
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install moviepy requests google-auth \
            google-auth-oauthlib google-api-python-client imageio[ffmpeg]
          python -m pip show moviepy

      - name: Run bot
        env:
          BARK_AUDIO_URL: ${{ secrets.BARK_AUDIO_URL }}
          YT_CREDS_JSON: ${{ secrets.YT_CREDS_JSON }}
        run: |
          which python
          python main.py
